import type { Metadata } from "next";
import { Josefin_Sans, Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../redux/provider";
import { Toaster } from "react-hot-toast";
import { CheckUser } from "@/components/Secure/CheckUser";
import WebSocketProvider from '../redux/WebSocketProvider';

const Josefin = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${Josefin.variable}`} cz-shortcut-listen="true">
        <ReduxProvider>
          <CheckUser>
            <WebSocketProvider>
            {children}
            <Toaster position="top-right" />
            </WebSocketProvider>
          </CheckUser>
        </ReduxProvider>
      </body>
    </html>
  );
}
